routes/web.php
<?php

use App\Containers\TelegramContest\Http\Controllers\TelegramContestController;
use Illuminate\Support\Facades\Route;
use Telegram\Bot\Laravel\Facades\Telegram;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
require __DIR__ . '/auth.php';

Route::get('/', function () {return view('index');})
    ->middleware(['auth'])
    ->name('index');


Route::resource('telegram-contest', TelegramContestController::class)
    ->middleware(['auth'])
    ->names('telegram-contest');


Route::post(\Telegram::getAccessToken() . '/webhook', function () {
    //  $response = \Telegram::getMe();
    //  $botId = $response->getId();
    //  $firstName = $response->getFirstName();
    //  $username = $response->getUsername();
    //
    //https://api.telegram.org/bot1968880741:AAHioqDqcMPNEvUE_LQWzJWrZwxZgvujcX4/setwebhook?url=https://36ae-194-182-81-79.ngrok.io/1968880741:AAHioqDqcMPNEvUE_LQWzJWrZwxZgvujcX4/webhook

    $update = \Telegram::commandsHandler(true);
    return 'ok';
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Главная') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <h2>Добро пожаловать! </h2>
                    <p>Для того что-бы начать нужно:</p>
                    <ul>
                        <li>1. Перейти в раздел "Телеграм конкурсы"</li>
                        <li>2. Создать конкурс</li>
                        <li>3. Дождаться, когда появится победитель</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Contests') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="/css/app.css">
        <link rel="stylesheet" href="/css/bootstrap.min.css">
        <link rel="stylesheet" href="/css/main.css">

{{--        <link rel="stylesheet" href="{{ asset('css/app.css') }}">--}}
{{--        <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">--}}
{{--        <link rel="stylesheet" href="{{ asset('css/main.css') }}">--}}

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
        <script src="{{ asset('js/bootstrap.min.js') }}" defer></script>
        <script src="{{ asset('js/main.js') }}" defer></script>
    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @include('layouts.navigation')

            <!-- Page Heading -->
            <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header>

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>
    </body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="/css/app.css">
{{--        <link rel="stylesheet" href="{{ asset('css/app.css') }}">--}}

        <!-- Scripts -->
        <script src="/js/app.js" defer></script>
{{--        <script src="{{ asset('js/app.js') }}" defer></script>--}}
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts/navigation.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="flex-shrink-0 flex items-center">
                    <a href="{{ route('index') }}">
                        <x-application-logo class="block h-10 w-auto fill-current text-gray-600" />
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-nav-link :href="route('index')" :active="request()->routeIs('index')">
                        {{ __('Главная') }}
                    </x-nav-link>
                </div>
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-nav-link :href="route('telegram-contest.index')" :active="request()->routeIs('telegram-contest')">
                        {{ __('Телеграм конкурсы') }}
                    </x-nav-link>
                </div>
            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <x-dropdown align="right" width="48">
                    <x-slot name="trigger">
                        <button class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                            <div>{{ Auth::user()->name }}</div>

                            <div class="ml-1">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                </svg>
                            </div>
                        </button>
                    </x-slot>

                    <x-slot name="content">
                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-dropdown-link :href="route('logout')"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                {{ __('Log Out') }}
                            </x-dropdown-link>
                        </form>
                    </x-slot>
                </x-dropdown>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-responsive-nav-link :href="route('index')" :active="request()->routeIs('index')">
                {{ __('Dashboard') }}
            </x-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="px-4">
                <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-responsive-nav-link :href="route('logout')"
                            onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Log Out') }}
                    </x-responsive-nav-link>
                </form>
            </div>
        </div>
    </div>
</nav>

resources/views/telegram-contest/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Создание конкурса для телеграма') }}
        </h2>
    </x-slot>

    <div class="container mt-5 bg-white p-5">
        <div class="row">
        <div class="col-sm-12 offset-md-3 col-md-6">
            <form method="POST" action="{{ route('telegram-contest.store') }}" class="needs-validation" novalidate>
                @csrf
                @method('POST')
                @error('exception')
                    <div class="alert alert-danger d-flex align-items-center" role="alert">
                        <div>{{$message}}</div>
                    </div>
                @enderror
                <div class="mb-3">
                    <label for="name" class="form-label">Название</label>
                    <input id="name" name="name" type="text" value="{{old('name')}}" class="form-control" >
                    @error('name')
                        <span class="text-danger" >{{ $message }}</span>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="status_id" class="form-label">Статус конкурса</label>
                    <select class="form-select" name="status_id" required>
                        @foreach($contestStatuses as $name => $id)
                            <option
                                @if (old('name') == $name)
                                    selected
                                @elseif ($loop->first)
                                    selected
                                @endif
                                value="{{$id}}">{{$name}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="mb-3">
                    <label for="count_winners" class="form-label">Количество победителей</label>
                    <input id="count_winners" name="count_winners"  type="number" class="form-control" value="{{old('count_winners')}}">
                    @error('count_winners')
                        <span class="text-danger" >{{ $message }}</span>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="date_end" class="form-label">Время запуска скрипта поиска победителей.</label>
                    <input id="date_end" name="date_end" type="datetime-local"  class="form-control" value="{{old('date_end')}}">
                    @error('date_end')
                        <span class="text-danger" >{{ $message }}</span>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="description" class="form-label">Описание</label>
                    <textarea class="form-control" name="description" id="description" cols="30" rows="4">{{old('description')}}</textarea>

                </div>
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <button class="btn btn-success" type="submit">Создать</button>
                </div>
            </form>
        </div>
        </div>
    </div>
</x-app-layout>

resources/views/telegram-contest/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Редактирование конкурса') }} {{$contest->name}}
        </h2>
    </x-slot>

    <div class="container mt-5 bg-white p-5">
        <div class="row">
        <div class="col-sm-12 offset-md-3 col-md-6">
            <form method="POST" action="{{ route('telegram-contest.update', $contest->id) }}">
                @csrf
                @method('PUT')
                @error('exception')
                <div class="alert alert-danger d-flex align-items-center" role="alert">
                    <div>{{$message}}</div>
                </div>
                @enderror


                <div class=" mb-3">
                    <label for="name" class="form-label">Название</label>
                    <input id="name" name="name" class="form-control" type="text" value="{{old('name', $contest->name)}}">
                    @error('name')
                    <span class="text-danger" >{{ $message }}</span>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="status_id" class="form-label">Статус конкурса</label>
                    <select class="form-select" name="status_id" required>
                        @foreach($contestStatuses as $name => $id)
                            <option
                                @if($id === $contest->status_id)
                                selected
                                @endif
                                value="{{$id}}">{{$name}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="mb-3">
                    <label for="count_winners" class="form-label">Количество победителей</label>
                    <input id="count_winners" name="count_winners"  type="number" class="form-control" value="{{old('count_winners', $contest->count_winners)}}">
                    @error('count_winners')
                        <span class="text-danger" >{{ $message }}</span>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="date_end" class="form-label">Время запуска скрипта поиска победителей.</label>
                    <input id="date_end" name="date_end" type="datetime-local"  class="form-control" value="{{old('date_end', $contest->date_end)}}">
                    @error('date_end')
                        <span class="text-danger" >{{ $message }}</span>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="description" class="form-label">Описание</label>
                    <textarea class="form-control" name="description" id="description" cols="30" rows="4">{{old('description', $contest->description)}}</textarea>
                    @error('description')
                        <span class="text-danger" >{{ $message }}</span>
                    @enderror
                </div>
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <button class="btn btn-success" type="submit">Изменить</button>
                </div>
            </form>
        </div>
        </div>
    </div>
</x-app-layout>

resources/views/telegram-contest/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Телеграм конкурсы') }}
        </h2>
    </x-slot>

    <div class="container mt-5 bg-white p-5">
        <div class="col-12">
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item" role="presentation">
                    <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true">Активные</button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile" type="button" role="tab" aria-controls="profile" aria-selected="false">Завершенные</button>
                </li>
            </ul>
            <div class="tab-content" id="myTabContent">

                <a href="{{route('telegram-contest.create')}}" class="btn btn-success mt-4">Добавить конкурс</a>

                <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                    <table class="table mt-3 table-hover">
                        <thead>
                        <tr class="table-light">
                            <th scope="col">#</th>
                            <th scope="col">Название</th>
                            <th scope="col">Описание</th>
                            <th scope="col">Статус</th>
                            <th scope="col">Кол-во участников</th>
                            <th scope="col">Кол-во победителей</th>
                            <th scope="col">Дата подведения итогов</th>
                            <th scope="col">Создан</th>
                            <th scope="col">Изменен</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if($contests)
                            @foreach($contests as $contest)
                                @if($contest->status->id < \App\Containers\TelegramContest\Models\ContestStatus::ID_STATUS_DONE)
                                    <tr
                                        @if($contest->status_id === \App\Containers\TelegramContest\Models\ContestStatus::ID_STATUS_ACTIVE)
                                            class="table-success"
                                        @endif
                                        @if($contest->status_id === \App\Containers\TelegramContest\Models\ContestStatus::ID_STATUS_PENDING)
                                            class="table-warning"
                                        @endif
                                    >
                                        <th scope="row">{{$loop->index}}</th>
                                        <td><a href="{{route('telegram-contest.show', $contest->id)}}">{{$contest->name}}</a> </td>
                                        <td>{{$contest->description}}</td>
                                        <td>{{$contest->status->name}}</td>
                                        <td>{{$contest->participants->count()}}</td>
                                        <td>{{$contest->winners->count()}}</td>
                                        <td>{{$contest->date_end}}</td>
                                        <td>{{$contest->created_at}}</td>
                                        <td>{{$contest->updated_at}}</td>
                                    </tr>
                                @endif
                            @endforeach
                        @endif
                        </tbody>
                    </table>
                </div>
                <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                    <table class="table mt-3 table-hover">
                        <thead>
                        <tr class="table-light">
                            <th scope="col">#</th>
                            <th scope="col">Название</th>
                            <th scope="col">Описание</th>
                            <th scope="col">Статус</th>
                            <th scope="col">Кол-во участников</th>
                            <th scope="col">Кол-во победителей</th>
                            <th scope="col">Дата подведения итогов</th>
                            <th scope="col">Создан</th>
                            <th scope="col">Изменен</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if($contests)
                            @foreach($contests as $contest)
                                @if($contest->status->id == \App\Containers\TelegramContest\Models\ContestStatus::ID_STATUS_DONE)
                                    <tr>
                                        <th scope="row">{{$loop->index}}</th>
                                        <td><a href="{{route('telegram-contest.show', $contest->id)}}">{{$contest->name}}</a></td>
                                        <td>{{$contest->description}}</td>
                                        <td>{{$contest->status->name}}</td>
                                        <td>{{$contest->participants->count()}}</td>
                                        <td>{{$contest->winners->count()}}</td>
                                        <td>{{$contest->date_end}}</td>
                                        <td>{{$contest->created_at}}</td>
                                        <td>{{$contest->updated_at}}</td>
                                    </tr>
                                @endif
                            @endforeach
                        @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/telegram-contest/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ $contest->name }}
        </h2>
    </x-slot>

    <div class="container mt-5 bg-white p-5">
        <div class="col-12">
                <a href="{{route('telegram-contest.edit', $contest->id)}}" class="btn btn-success mt-4">Редактировать</a>
                <form class="d-inline-block" method="POST" action="{{route('telegram-contest.destroy', $contest->id)}}">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger mt-4"
                            onclick="return confirm('Подтверждаете удаление ?')"
                            type="submit">Удалить
                    </button>
                </form>

        </div>

        <div class="col-12 mt-5">
            <ul class="nav nav-tabs mb-5" id="myTab" role="tablist">
                <li class="nav-item" role="presentation">
                    <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home"
                            type="button" role="tab" aria-controls="home" aria-selected="true">Общие данные
                    </button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="participants-tab" data-bs-toggle="tab" data-bs-target="#participants"
                            type="button" role="tab" aria-controls="participants" aria-selected="false">Участники
                    </button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="winners-tab" data-bs-toggle="tab" data-bs-target="#winners"
                            type="button" role="tab" aria-controls="winners" aria-selected="false">Победители
                    </button>
                </li>
            </ul>
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                    <div class="col-6 offset-3">
                        <table class="table table-striped">
                            <tbody>
                            <tr>
                                <th scope="row">Название</th>
                                <td>{{$contest->name}}</td>
                            </tr>

                            <tr>
                                <th scope="row">Количество победителей</th>
                                <td>{{$contest->count_winners}}</td>
                            </tr>
                            <tr>
                                <th scope="row">Статус</th>
                                <td>{{$contest->status->name}}</td>
                            </tr>
                            <tr>
                                <th scope="row">Дата подведения итогов</th>
                                <td>{{$contest->date_end}}</td>
                            </tr>
                            <tr>
                                <th scope="row">Описание</th>
                                <td>{{$contest->description}}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="tab-pane fade" id="participants" role="tabpanel" aria-labelledby="participants-tab">
                    @if ( count($contest->participants) > 0)
                        <table class="table mt-3 table-sm">
                            <thead>
                            <tr class="table-light">
                                <th scope="col">#</th>
                                <th scope="col">ID</th>
                                <th scope="col">ID в телеграме</th>
                                <th scope="col">Ник</th>
                                <th scope="col">Имя</th>
                                <th scope="col">Фамилия</th>
                            </tr>
                            </thead>
                            <tbody>

                            @foreach($contest->participants as $participant)
                                <tr>
                                    <th scope="row">{{$loop->index}}</th>
                                    <td>{{$participant->id}}</td>
                                    <td>{{$participant->telegram_user->telegram_id}}</td>
                                    <td>{{$participant->telegram_user->username}}</td>
                                    <td>{{$participant->telegram_user->first_name}}</td>
                                    <td>{{$participant->telegram_user->last_name}}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    @else
                        <div class="alert alert-success" role="alert">
                            <h4 class="alert-heading">Пока никто не зарегистрировался на конкурс!</h4>
                            <p>Еще нет участников, как только человек подтвердит свое участие, тут отобразится таблица с
                                участниками </p>
                            <hr>
                            <p class="mb-0">Как запустить конкурс можно прочитать <a href="#">тут</a></p>
                        </div>
                    @endif
                </div>
                <div class="tab-pane fade" id="winners" role="tabpanel" aria-labelledby="winners-tab">
                    @if ( count($contest->winners) > 0)
                        <table class="table mt-3 table-sm">
                            <thead>
                            <tr class="table-success">
                                <th scope="col">#</th>
                                <th scope="col">ID</th>
                                <th scope="col">ID в телеграме</th>
                                <th scope="col">Ник</th>
                                <th scope="col">Имя</th>
                                <th scope="col">Фамилия</th>
                            </tr>
                            </thead>
                            <tbody>

                            @foreach($contest->winners as $winner)
                                <tr>
                                    <th scope="row">{{$loop->index}}</th>
                                    <td>{{$winner->id}}</td>
                                    <td>{{$winner->telegram_user->telegram_id}}</td>
                                    <td>{{$winner->telegram_user->username}}</td>
                                    <td>{{$winner->telegram_user->first_name}}</td>
                                    <td>{{$winner->telegram_user->last_name}}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    @else
                        <div class="alert alert-info" role="alert">
                            Нет победителей
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</x-app-layout>